//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.17 at 09:53:25 AM EDT 
//


package org.ctdbase.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *                 A chemical-gene interaction.
 *                 An interaction consists of two or more actors connected by one or more actions.
 *                 An actor is either a chemical, a gene or a nested sub-interaction.
 *                 An action is a physical, regulatory or biochemical interaction between actors.
 *                 An interaction is reported in zero, one or more taxa (organisms), and is cited in one or more literature
 *                 references.
 *             
 * 
 * <p>Java class for ixnType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ixnType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="taxon" type="{}taxonType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="reference" type="{}referenceType" maxOccurs="unbounded"/>
 *         &lt;element name="axn" type="{}axnType" maxOccurs="unbounded"/>
 *         &lt;element name="actor" type="{}actorType" maxOccurs="unbounded" minOccurs="2"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}long" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ixnType", propOrder = {
    "taxon",
    "reference",
    "axn",
    "actor"
})
public class IxnType {

    protected List<TaxonType> taxon;
    @XmlElement(required = true)
    protected List<ReferenceType> reference;
    @XmlElement(required = true)
    protected List<AxnType> axn;
    @XmlElement(required = true)
    protected List<ActorType> actor;
    @XmlAttribute(name = "id", required = true)
    protected long id;

    /**
     * Gets the value of the taxon property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the taxon property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTaxon().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TaxonType }
     * 
     * 
     */
    public List<TaxonType> getTaxon() {
        if (taxon == null) {
            taxon = new ArrayList<TaxonType>();
        }
        return this.taxon;
    }

    /**
     * Gets the value of the reference property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the reference property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReference().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ReferenceType }
     * 
     * 
     */
    public List<ReferenceType> getReference() {
        if (reference == null) {
            reference = new ArrayList<ReferenceType>();
        }
        return this.reference;
    }

    /**
     * Gets the value of the axn property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the axn property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAxn().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AxnType }
     * 
     * 
     */
    public List<AxnType> getAxn() {
        if (axn == null) {
            axn = new ArrayList<AxnType>();
        }
        return this.axn;
    }

    /**
     * Gets the value of the actor property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the actor property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getActor().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ActorType }
     * 
     * 
     */
    public List<ActorType> getActor() {
        if (actor == null) {
            actor = new ArrayList<ActorType>();
        }
        return this.actor;
    }

    /**
     * Gets the value of the id property.
     * 
     */
    public long getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(long value) {
        this.id = value;
    }

}
