//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.17 at 09:53:25 AM EDT 
//


package org.ctdbase.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.ctdbase.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Ixnset_QNAME = new QName("", "ixnset");
    private final static QName _ActorTypeAxn_QNAME = new QName("", "axn");
    private final static QName _ActorTypeActor_QNAME = new QName("", "actor");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.ctdbase.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link IxnSetType }
     * 
     */
    public IxnSetType createIxnSetType() {
        return new IxnSetType();
    }

    /**
     * Create an instance of {@link ActorType }
     * 
     */
    public ActorType createActorType() {
        return new ActorType();
    }

    /**
     * Create an instance of {@link AxnType }
     * 
     */
    public AxnType createAxnType() {
        return new AxnType();
    }

    /**
     * Create an instance of {@link ReferenceType }
     * 
     */
    public ReferenceType createReferenceType() {
        return new ReferenceType();
    }

    /**
     * Create an instance of {@link TaxonType }
     * 
     */
    public TaxonType createTaxonType() {
        return new TaxonType();
    }

    /**
     * Create an instance of {@link IxnType }
     * 
     */
    public IxnType createIxnType() {
        return new IxnType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IxnSetType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ixnset")
    public JAXBElement<IxnSetType> createIxnset(IxnSetType value) {
        return new JAXBElement<IxnSetType>(_Ixnset_QNAME, IxnSetType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AxnType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "axn", scope = ActorType.class)
    public JAXBElement<AxnType> createActorTypeAxn(AxnType value) {
        return new JAXBElement<AxnType>(_ActorTypeAxn_QNAME, AxnType.class, ActorType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ActorType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "actor", scope = ActorType.class)
    public JAXBElement<ActorType> createActorTypeActor(ActorType value) {
        return new JAXBElement<ActorType>(_ActorTypeActor_QNAME, ActorType.class, ActorType.class, value);
    }

}
